training:
  batch_size: 32
  n_epochs: 100
  n_epochs_ori: 500000
  n_iters: 300001
  log_all_sigmas: false

device: cuda:0

sampling:
  batch_size: 100
  data_init: false
  step_lr: 0.0000062
  n_steps_each: 5
  ckpt_id: 300000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15

fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000062
  n_steps_each: 5
  begin_ckpt: 5000
  end_ckpt: 300000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 300
  end_ckpt: 300
  batch_size: 100

data:
  dataset: "GMM"
  dim: 10
  image_size: 28
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 4

model:
  sigma_begin: 1
  num_classes: 200
  ori_num_classes: 50
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  ori_sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  lr_ori: 0.00005
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
